services:
  frontend:
    container_name: portfolio_frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5174:80"  # host 5174 â†’ contenedor 80
    restart: unless-stopped
